apiVersion: v1
kind: Service
metadata:
  name: tasks-backend-loadbalancer
spec:
  selector:
    app: tasks-backend
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: tasks-database-connection
spec:
  selector:
    app: tasks-database
  ports:
    - port: 3306
  clusterIP: None
